# **Ordinal Encoding**
It is used to convert categorical data(ordinal) into numerical data. It must be used on the ordinal data as when your data have some order.

In [151]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [152]:
df = pd.read_csv("data/titanic.csv", usecols=["Survived", "Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"])
df["Embarked"] = df["Embarked"].fillna(df["Age"].mode()[0])
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [153]:
# i want to create a new col base on pclass and fare

def level(row):
    if row==1:
        return "high"
    elif row==2:
        return "middle"
    else:
        return "low"
    

df["Fare_level"] = df["Pclass"].apply(level)

In [154]:
df["Family"] = df["SibSp"]+df["Parch"]

In [155]:
sorted(df["Family"].unique().tolist())

[0, 1, 2, 3, 4, 5, 6, 7, 10]

In [156]:
def f_level(row):
    if row<5:
        return "low"
    else:
        return "high"

In [157]:
df["Family_level"] = df["Family"].apply(f_level)

In [158]:
df.sample(5)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Fare_level,Family,Family_level
139,0,1,male,24.0,0,0,79.2000,C,high,0,low
212,0,3,male,22.0,0,0,7.2500,S,low,0,low
694,0,1,male,60.0,0,0,26.5500,S,high,0,low
608,1,2,female,22.0,1,2,41.5792,C,middle,3,low
585,1,1,female,18.0,0,2,79.6500,S,high,2,low

In [159]:
df.groupby(df["Fare_level"])["Fare"].mean()

Fare_level
high      84.154687
low       13.675550
middle    20.662183
Name: Fare, dtype: float64

In [160]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Fare_level,Family,Family_level
0,0,3,male,22.0,1,0,7.2500,S,low,1,low
1,1,1,female,38.0,1,0,71.2833,C,high,1,low
2,1,3,female,26.0,0,0,7.9250,S,low,0,low
3,1,1,female,35.0,1,0,53.1000,S,high,1,low
4,0,3,male,35.0,0,0,8.0500,S,low,0,low

In [161]:

X = df.drop(columns=["Survived"])
y = df["Survived"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [162]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[["low", "middle", "high"]], dtype=int)

encoder.fit(X_train[["Fare_level"]])

OrdinalEncoder(categories=[['low', 'middle', 'high']], dtype=<class 'int'>)

In [163]:
X_train["level_encode"] = encoder.transform(X_train[["Fare_level"]])
X_test["level_encode"] = encoder.transform(X_test[["Fare_level"]])

In [164]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Fare_level,Family,Family_level,level_encode
331,1,male,45.500000,0,0,28.5000,S,high,0,low,2
733,2,male,23.000000,0,0,13.0000,S,middle,0,low,1
382,3,male,32.000000,0,0,7.9250,S,low,0,low,0
704,3,male,26.000000,1,0,7.8542,S,low,1,low,0
813,3,female,6.000000,4,2,31.2750,S,low,6,high,0
...,...,...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,S,low,0,low,0
270,1,male,29.699118,0,0,31.0000,S,high,0,low,2
860,3,male,41.000000,2,0,14.1083,S,low,2,low,0
435,1,female,14.000000,1,2,120.0000,S,high,3,low,2
102,1,male,21.000000,0,1,77.2875,S,high,1,low,2

In [165]:
encoder.categories

[['low', 'middle', 'high']]

In [166]:
# if i want to inverse transform

X_train["inverse"] = encoder.inverse_transform(X_train[["level_encode"]]).ravel()
X_test["inverse"] = encoder.inverse_transform(X_test[["level_encode"]]).ravel()

In [167]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Fare_level,Family,Family_level,level_encode,inverse
331,1,male,45.500000,0,0,28.5000,S,high,0,low,2,high
733,2,male,23.000000,0,0,13.0000,S,middle,0,low,1,middle
382,3,male,32.000000,0,0,7.9250,S,low,0,low,0,low
704,3,male,26.000000,1,0,7.8542,S,low,1,low,0,low
813,3,female,6.000000,4,2,31.2750,S,low,6,high,0,low
...,...,...,...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,S,low,0,low,0,low
270,1,male,29.699118,0,0,31.0000,S,high,0,low,2,high
860,3,male,41.000000,2,0,14.1083,S,low,2,low,0,low
435,1,female,14.000000,1,2,120.0000,S,high,3,low,2,high
102,1,male,21.000000,0,1,77.2875,S,high,1,low,2,high

In [168]:
# encoding more than one variable

X_train.drop(columns=["level_encode", "inverse"], inplace=True)
X_test.drop(columns=["level_encode", "inverse"], inplace=True)

In [169]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Fare_level,Family,Family_level
331,1,male,45.500000,0,0,28.5000,S,high,0,low
733,2,male,23.000000,0,0,13.0000,S,middle,0,low
382,3,male,32.000000,0,0,7.9250,S,low,0,low
704,3,male,26.000000,1,0,7.8542,S,low,1,low
813,3,female,6.000000,4,2,31.2750,S,low,6,high
...,...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,S,low,0,low
270,1,male,29.699118,0,0,31.0000,S,high,0,low
860,3,male,41.000000,2,0,14.1083,S,low,2,low
435,1,female,14.000000,1,2,120.0000,S,high,3,low
102,1,male,21.000000,0,1,77.2875,S,high,1,low

In [170]:
# applying ordinal encoding on multiple variable(columns)

encode = OrdinalEncoder(categories=[["low", "middle", "high"], ["high", "low"]], dtype=int)

In [171]:
encode.fit(X_train[["Fare_level", "Family_level"]])

OrdinalEncoder(categories=[['low', 'middle', 'high'], ['high', 'low']],
               dtype=<class 'int'>)

In [172]:
X_train[["Fare_level_encode", "Family_level_encode"]] = encode.transform(X_train[["Fare_level", "Family_level"]])
X_test[["Fare_level_encode", "Family_level_encode"]] = encode.transform(X_test[["Fare_level", "Family_level"]])

In [174]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Fare_level,Family,Family_level,Fare_level_encode,Family_level_encode
331,1,male,45.500000,0,0,28.5000,S,high,0,low,2,1
733,2,male,23.000000,0,0,13.0000,S,middle,0,low,1,1
382,3,male,32.000000,0,0,7.9250,S,low,0,low,0,1
704,3,male,26.000000,1,0,7.8542,S,low,1,low,0,1
813,3,female,6.000000,4,2,31.2750,S,low,6,high,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,S,low,0,low,0,1
270,1,male,29.699118,0,0,31.0000,S,high,0,low,2,1
860,3,male,41.000000,2,0,14.1083,S,low,2,low,0,1
435,1,female,14.000000,1,2,120.0000,S,high,3,low,2,1
102,1,male,21.000000,0,1,77.2875,S,high,1,low,2,1

In [175]:
encode.categories

[['low', 'middle', 'high'], ['high', 'low']]