# **Handling mixed variable/column**

Mixed variable are those variable or columns which contains both numeric and alphabetic values.

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv("data/titanic.csv", usecols=["Embarked", "Cabin"])

In [44]:
df.head()

  Cabin Embarked
0   NaN        S
1   C85        C
2   NaN        S
3  C123        S
4   NaN        S

In [45]:
df[df["Embarked"].isna()]

    Cabin Embarked
61    B28      NaN
829   B28      NaN

In [46]:
# This is just for making mixed variable to practice

df.loc[61, "Embarked"] = "1"

In [47]:
df.loc[829, "Embarked"] = "2"

In [48]:
df["Cabin"] = df["Cabin"].fillna(df["Cabin"].mode()[0])

In [49]:
df.head()

     Cabin Embarked
0  B96 B98        S
1      C85        C
2  B96 B98        S
3     C123        S
4  B96 B98        S

In [50]:
# split the cabin column to separate alphabetic and numeric

df["cabin_num"] = df["Cabin"].str.findall(r"\d+").str.join(" ")

In [51]:


df["cabin_cat"] = df["Cabin"].str.findall(r'[A-Za-z]+').str.join(" ")

In [52]:
df.head()

     Cabin Embarked cabin_num cabin_cat
0  B96 B98        S     96 98       B B
1      C85        C        85         C
2  B96 B98        S     96 98       B B
3     C123        S       123         C
4  B96 B98        S     96 98       B B

In [53]:
# now it time to separate embarked as it contain sometimes numeric and sometime categorical
df["Embarked"].unique()

array(['S', 'C', 'Q', '1', '2'], dtype=object)

In [60]:
df["Embarked_num"] = pd.to_numeric(df["Embarked"], errors="coerce", downcast="integer")

In [61]:
df["Embarked_cat"] = np.where(df["Embarked_num"].isna(), df["Embarked"], np.nan)

In [ ]:
temp = df.sample(10)

for i in df["Embarked_num"]:
    if i==1:
        print(i)
        break

In [218]:
da = pd.DataFrame()

while True:
    tem = df.sample(10)
    if tem[(tem["Embarked_num"]==1) | (tem["Embarked_num"]==2)].shape[0]>0:
        da = tem
        break

In [219]:
da

       Cabin Embarked cabin_num cabin_cat Embarked_cat  Embarked_num
634  B96 B98        S     96 98       B B            S           NaN
502  B96 B98        Q     96 98       B B            Q           NaN
6        E46        S        46         E            S           NaN
531  B96 B98        C     96 98       B B            C           NaN
117  B96 B98        S     96 98       B B            S           NaN
829      B28        2        28         B          NaN           2.0
192  B96 B98        S     96 98       B B            S           NaN
105  B96 B98        S     96 98       B B            S           NaN
605  B96 B98        S     96 98       B B            S           NaN
497  B96 B98        S     96 98       B B            S           NaN