# **Trimming**

The process of completely deleting data points that fall outside a defined upper or lower limit.


# **Capping**
 The process of replacing outlier values with a specified maximum or minimum threshold rather than deleting them.

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("data/titanic.csv").drop(columns=["PassengerId", "Name", "Ticket", "Name", "Cabin"])

In [11]:
q1 = np.percentile(df["Fare"], 25)
q3 = np.percentile(df["Fare"], 75)
iqr = q3-q1

lower_limit = q1-(iqr*1.5)
upper_limit = q3+(iqr*1.5)


df[(df["Fare"]<lower_limit) | (df["Fare"]>upper_limit)]

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
1           1       1  female  38.0      1      0   71.2833        C
27          0       1    male  19.0      3      2  263.0000        S
31          1       1  female   NaN      1      0  146.5208        C
34          0       1    male  28.0      1      0   82.1708        C
52          1       1  female  49.0      1      0   76.7292        C
..        ...     ...     ...   ...    ...    ...       ...      ...
846         0       3    male   NaN      8      2   69.5500        S
849         1       1  female   NaN      1      0   89.1042        C
856         1       1  female  45.0      1      1  164.8667        S
863         0       3  female   NaN      8      2   69.5500        S
879         1       1  female  56.0      0      1   83.1583        C

[116 rows x 8 columns]

In [12]:
# trimming

df[(df["Fare"]>lower_limit) & (df["Fare"]<upper_limit)]

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
5           0       3    male   NaN      0      0   8.4583        Q
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[775 rows x 8 columns]

In [13]:
# capping 

df["cap_fare"] = df["Fare"].clip(lower_limit, upper_limit)

In [17]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  cap_fare
0           0       3    male  22.0      1      0   7.2500        S    7.2500
1           1       1  female  38.0      1      0  71.2833        C   65.6344
2           1       3  female  26.0      0      0   7.9250        S    7.9250
3           1       1  female  35.0      1      0  53.1000        S   53.1000
4           0       3    male  35.0      0      0   8.0500        S    8.0500
..        ...     ...     ...   ...    ...    ...      ...      ...       ...
886         0       2    male  27.0      0      0  13.0000        S   13.0000
887         1       1  female  19.0      0      0  30.0000        S   30.0000
888         0       3  female   NaN      1      2  23.4500        S   23.4500
889         1       1    male  26.0      0      0  30.0000        C   30.0000
890         0       3    male  32.0      0      0   7.7500        Q    7.7500

[891 rows x 9 columns]